Update action.yml

diff --git a/.github/actions/trivy-sca/action.yml b/.github/actions/trivy-sca/action.yml
--- a/.github/actions/trivy-sca/action.yml
+++ b/.github/actions/trivy-sca/action.yml
@@ -1,83 +1,292 @@
-name: "Trivy SCA Scan Action"
-description: "Reusable action for Trivy filesystem SCA + secret scanning"
+name: 'Trivy SCA Scan Action'
 
+description: 'Reusable action for Trivy SCA scan'
+
+inputs:
+
+  severity:
+
+    description: 'Severity levels to report.'
+
+    required: false
+
+    default: 'HIGH,CRITICAL'
+
+  scanners:
+
+    description: 'Trivy scanners to enable (e.g., vuln,secret,config).'
+
+    required: false
+
+    default: 'vuln'
+
+  skip_dirs:
+
+    description: 'Comma-separated list of directories to skip during the scan.'
+
+    required: false
+
+    default: 'venv,build,dist'
+
+  skip_files:
+
+    description: 'Comma-separated list of files to skip during the scan.'
+
+    required: false
+
+    default: ''
+
+  version:
+
+    description: 'Trivy version to install (e.g., 0.69.3). If set to 0.69.4, installation is skipped.'
+
+    required: false
+
+    default: '0.69.3'
+
+  add_summary:
+
+    description: 'Whether to add a summary of the Trivy scan results to the GitHub'
+
+    required: false
+
+    default: 'true'
+
+  upload_artifact:
+
+    description: 'Whether to upload the Trivy scan results as an artifact.'
+
+    required: false
+
+    default: 'true'
+ 
+outputs:
+
+  trivy_results:
+
+    description: 'Generated Scan results file'
+
+    value: ${{ steps.set_output.outputs.trivy_results }}
+ 
 runs:
-  using: "composite"
+
+  using: 'composite'
+
   steps:
+
     - name: Install Trivy
+
       shell: bash
+
       run: |
+
         set -euo pipefail
+
         REQ_VERSION="${{ inputs.version }}"
+
         if [[ "$REQ_VERSION" == "0.69.4" ]]; then
+
           echo "Requested version is 0.69.4 → ❌ skipping installation as 0.69.4 isn't allowed."
-          exit 1
+
         else
+
           echo "Installing Trivy $REQ_VERSION ..."
-          curl -fsSL "https://github.com/aquasecurity/trivy/releases/download/v${REQ_VERSION}/trivy_${REQ_VERSION}_Linux-64bit.tar.gz" \
+
+          curl -fsSL "https://github.com/aquasecurity/trivy/releases/download/v${REQ_VERSION}/trivy_${REQ_VERSION}_Linux-… \
+
             -o trivy.tgz
-          INSTALL_DIR="$HOME/.local/bin"
-          mkdir -p "$INSTALL_DIR"
-          tar -xzf trivy.tgz -C "$INSTALL_DIR"
+
+          sudo tar -C /usr/local/bin -xzf trivy.tgz trivy
+
           trivy --version
-        fi
 
+        fi
+ 
     - name: Run Trivy SCA
+
       shell: bash
+
       if: ${{ inputs.version != '0.69.4' }}
+
       env:
+
         COMPONENT_PATH: '.'
+
       run: |
+
         set -euo pipefail
+
         trivy fs \
+
           --scanners "${{ inputs.scanners }}" \
+
           --vuln-type library \
+
           --severity "${{ inputs.severity }}" \
+
           --ignore-unfixed \
+
           --list-all-pkgs \
+
           --skip-dirs "${{ inputs.skip_dirs }}" \
+
           --skip-files "${{ inputs.skip_files }}" \
+
           --format table \
+
           . | tee "trivy-results.txt"
-
+ 
     - name: Set output
+
       id: set_output
+
       shell: bash
+
       if: ${{ inputs.version != '0.69.4' }}
+
       run: |
+
         set -euo pipefail
+
         echo "trivy_results=trivy-results.txt" >> $GITHUB_OUTPUT
-
+ 
     - name: Add Trivy table to Summary
-      if: ${{ inputs.add_summary != 'false' && steps.set_output.outputs.trivy_results != '' }}
-      shell: bash
-      run: |
-        echo "## Trivy Report Summary" >> $GITHUB_STEP_SUMMARY
-        echo '```' >> $GITHUB_STEP_SUMMARY
-        sed -n '3,11p' ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY
-        echo '```' >> $GITHUB_STEP_SUMMARY
-        echo "## Trivy Scan Results" >> $GITHUB_STEP_SUMMARY
-        TOTAL=$(grep -oE 'Total:[[:space:]]*[0-9]+' ${{ steps.set_output.outputs.trivy_results }} | head -1 | grep -oE '[0-9]+' || true)
-        if [ -z "$TOTAL" ]; then
-          echo "<span style='color:orange'>⚠️ No files are required to be scaned for SCA </span>" >> $GITHUB_STEP_SUMMARY
-        elif [ "$TOTAL" -eq 0 ]; then
-          echo "<span style='color:green'>✅ **No vulnerabilities found** </span>" >> $GITHUB_STEP_SUMMARY
-        elif [ "$TOTAL" -ne 0 ]; then
-          echo "<span style='color:red'>❌ **Total vulnerabilities :** $TOTAL</span>" >> $GITHUB_STEP_SUMMARY
-        else
-          echo "<span style='color:orange'>⚠️ File formate is changed </span>" >> $GITHUB_STEP_SUMMARY
-        fi
-        echo "<details><summary>Full Trivy Output</summary>" >> $GITHUB_STEP_SUMMARY
-        echo "<pre>" >> $GITHUB_STEP_SUMMARY
-        tail -n +25 ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY 
-        echo "</pre>" >> $GITHUB_STEP_SUMMARY
-        echo "</details>" >> $GITHUB_STEP_SUMMARY
 
-    - name: Run Trivy SCA Scan
-      uses: aquasecurity/trivy-action@0.20.0
+      if: ${{ inputs.add_summary != 'false' && steps.set_output.outputs.trivy_results != '' }}
+
+      shell: bash
+
+      run: |
+
+        echo "## Trivy Report Summary" >> $GITHUB_STEP_SUMMARY
+
+        echo '```' >> $GITHUB_STEP_SUMMARY
+
+        sed -n '3,11p' ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY
+
+        echo '```' >> $GITHUB_STEP_SUMMARY
+
+        echo "## Trivy Scan Results" >> $GITHUB_STEP_SUMMARY
+
+        TOTAL=$(grep -oE 'Total:[[:space:]]*[0-9]+' ${{ steps.set_output.outputs.trivy_results }} | head -1 | grep -oE '[0-9]+' || true)
+
+        if [ -z "$TOTAL" ]; then
+
+          echo "<span style='color:orange'>⚠️ No files are required to be scaned for SCA </span>" >> $GITHUB_STEP_SUMMARY
+
+        elif [ "$TOTAL" -eq 0 ]; then
+
+          echo "<span style='color:green'>✅ Total vulnerabilities: $TOTAL</span>" >> $GITHUB_STEP_SUMMARY
+
+        elif [ "$TOTAL" -ne 0 ]; then
+
+          echo "<span style='color:red'>❌ Total vulnerabilities: $TOTAL</span>" >> $GITHUB_STEP_SUMMARY
+
+        else
+
+          echo "<span style='color:orange'>⚠️ File formate is changed </span>" >> $GITHUB_STEP_SUMMARY
+
+        fi
+
+        echo '```' >> $GITHUB_STEP_SUMMARY
+
+        tail -n +25 ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY
+
+        echo '```' >> $GITHUB_STEP_SUMMARY
+ 
+    - name: Upload trivy-results as artifact
+
+      if: ${{ inputs.upload_artifact != 'false' }}
+
+      uses: actions/upload-artifact@v4
+
       with:
-        scan-type: "fs"
-        scanners: "vuln,secret"
-        severity: "HIGH,CRITICAL"
-        ignore-unfixed: true
-        exit-code: 1
+
+        name: trivy-results
+
+        path: ${{ steps.set_output.outputs.trivy_results }}
+
+ 
+# name: "Trivy SCA Scan Action"
+# description: "Reusable action for Trivy filesystem SCA + secret scanning"
+
+# runs:
+#   using: "composite"
+#   steps:
+#     - name: Install Trivy
+#       shell: bash
+#       run: |
+#         set -euo pipefail
+#         REQ_VERSION="${{ inputs.version }}"
+#         if [[ "$REQ_VERSION" == "0.69.4" ]]; then
+#           echo "Requested version is 0.69.4 → ❌ skipping installation as 0.69.4 isn't allowed."
+#           exit 1
+#         else
+#           echo "Installing Trivy $REQ_VERSION ..."
+#           curl -fsSL "https://github.com/aquasecurity/trivy/releases/download/v${REQ_VERSION}/trivy_${REQ_VERSION}_Linux-64bit.tar.gz" \
+#             -o trivy.tgz
+#           INSTALL_DIR="$HOME/.local/bin"
+#           mkdir -p "$INSTALL_DIR"
+#           tar -xzf trivy.tgz -C "$INSTALL_DIR"
+#           trivy --version
+#         fi
+
+#     - name: Run Trivy SCA
+#       shell: bash
+#       if: ${{ inputs.version != '0.69.4' }}
+#       env:
+#         COMPONENT_PATH: '.'
+#       run: |
+#         set -euo pipefail
+#         trivy fs \
+#           --scanners "${{ inputs.scanners }}" \
+#           --vuln-type library \
+#           --severity "${{ inputs.severity }}" \
+#           --ignore-unfixed \
+#           --list-all-pkgs \
+#           --skip-dirs "${{ inputs.skip_dirs }}" \
+#           --skip-files "${{ inputs.skip_files }}" \
+#           --format table \
+#           . | tee "trivy-results.txt"
+
+#     - name: Set output
+#       id: set_output
+#       shell: bash
+#       if: ${{ inputs.version != '0.69.4' }}
+#       run: |
+#         set -euo pipefail
+#         echo "trivy_results=trivy-results.txt" >> $GITHUB_OUTPUT
+
+#     - name: Add Trivy table to Summary
+#       if: ${{ inputs.add_summary != 'false' && steps.set_output.outputs.trivy_results != '' }}
+#       shell: bash
+#       run: |
+#         echo "## Trivy Report Summary" >> $GITHUB_STEP_SUMMARY
+#         echo '```' >> $GITHUB_STEP_SUMMARY
+#         sed -n '3,11p' ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY
+#         echo '```' >> $GITHUB_STEP_SUMMARY
+#         echo "## Trivy Scan Results" >> $GITHUB_STEP_SUMMARY
+#         TOTAL=$(grep -oE 'Total:[[:space:]]*[0-9]+' ${{ steps.set_output.outputs.trivy_results }} | head -1 | grep -oE '[0-9]+' || true)
+#         if [ -z "$TOTAL" ]; then
+#           echo "<span style='color:orange'>⚠️ No files are required to be scaned for SCA </span>" >> $GITHUB_STEP_SUMMARY
+#         elif [ "$TOTAL" -eq 0 ]; then
+#           echo "<span style='color:green'>✅ **No vulnerabilities found** </span>" >> $GITHUB_STEP_SUMMARY
+#         elif [ "$TOTAL" -ne 0 ]; then
+#           echo "<span style='color:red'>❌ **Total vulnerabilities :** $TOTAL</span>" >> $GITHUB_STEP_SUMMARY
+#         else
+#           echo "<span style='color:orange'>⚠️ File formate is changed </span>" >> $GITHUB_STEP_SUMMARY
+#         fi
+#         echo "<details><summary>Full Trivy Output</summary>" >> $GITHUB_STEP_SUMMARY
+#         echo "<pre>" >> $GITHUB_STEP_SUMMARY
+#         tail -n +25 ${{ steps.set_output.outputs.trivy_results }} >> $GITHUB_STEP_SUMMARY 
+#         echo "</pre>" >> $GITHUB_STEP_SUMMARY
+#         echo "</details>" >> $GITHUB_STEP_SUMMARY
+
+#     - name: Run Trivy SCA Scan
+#       uses: aquasecurity/trivy-action@0.20.0
+#       with:
+#         scan-type: "fs"
+#         scanners: "vuln,secret"
+#         severity: "HIGH,CRITICAL"
+#         ignore-unfixed: true
+#         exit-code: 1
